add optional kwargs to LitAPI methods
Lightning-AI/LitServe pull request #118
Opened 2024-05-28 17:30 UTC by aniketmaurya

This PR injects a meta dictionary to LitAPI methods which can be used to log important details that can be passed on from one method to another. 

**User impact**: `meta_kwargs` is an optional argument and users won't be forced to include it while defining the methods.

Example, we can track the number of tokens for token usage schema of `OpenAISpec`:

```python
import time
from typing import Optional

from transformers import pipeline
import litserve as ls
import logging

class GPT2LitAPI(ls.LitAPI):
    def setup(self, device):
        pass

    def predict(self, x, meta_kwargs): 
        meta_kwargs["num_tokens"] = 0
        for text in "this is a generated text".split():
            meta_kwargs["num_tokens"] += 1
            yield text + " "

    def encode_response(self, output, meta_kwargs):
        for e in super().encode_response(output):
           usage = {"num_tokens": meta_kwargs["num_tokens"]}
           # we can encode and return usage here
            yield e

if __name__ == '__main__':
    api = GPT2LitAPI()
    server = ls.LitServer(api, accelerator='auto', spec=ls.OpenAISpec())
    server.run(port=8000)
```

2024-05-30 11:21 UTC, williamFalcon commented
@aniketmaurya start the PR with a clear user story and why this is needed (now).

"When trying to do XYZ, this is not possible/had issue/whatever. this thing we are adding will enable XYZ and it's important because ABC."

2024-05-30 14:09 UTC, lantiga requested changes
To clarify, this PR will allow users to avoid antipatterns where context data is passed in the main payload if you need it. With this PR you can keep your payload clean (e.g. a tensor), let it batch automatically etc, and pass context data around.

Looks good overall, injection allows users to not think about context if they don't want to.
However the caveat is with unhappy paths: can you show what happens when a user passes two arguments to `predict`?

```
class SomeAPI(LitAPI):
    def predict(x, y):
        ...
```
this will be common, we need to avoid producing a confusing error from Python. If needed, let's catch this and override the error.

Also:
- let's rename the dict to `context` (see comment)
- we need tests

I'm wondering, can't we just have any kwargs after the first positional argument be context, instead of injecting?

2024-05-30 14:09 UTC, lantiga commented on src/litserve/server.py
> +    if "context_kwargs" in sig.parameters:
let's call it `context` instead of `context_kwargs` or `meta_kwargs`
let's also change the signature to `_inject_context` accordingly

2024-05-30 16:18 UTC, aniketmaurya commented
> *  However the caveat is with unhappy paths: can you show what happens when a user passes two arguments to predict?
  ```
  class SomeAPI(LitAPI):
      def predict(x, y):
          ...
  ```
[Right now](https://github.com/Lightning-AI/LitServe/blob/720740f08e7496b5de7100f18d9faf379ecbb441/src/litserve/server.py#L123-L125), we pass the decoded output to predict as it is, we don't differentiate if decode returns list or dict.



> * I'm wondering, can't we just have any kwargs after the first positional argument be context, instead of injecting?

If we unroll the kwargs, the objects like integer would be passed as a value instead of reference and any change in one method would not reflect in the other. 


will add tests soon, wanted to get first round of feedback first :D !

2024-05-30 19:21 UTC, lantiga commented
> [Right now](https://github.com/Lightning-AI/LitServe/blob/720740f08e7496b5de7100f18d9faf379ecbb441/src/litserve/server.py#L123-L125), we pass the decoded output to predict as it is, we don't differentiate if decode returns list or dict.

Right, I'm referring to the case where we pass 2 arguments to `predict`, not a list. Try to do that on this PR and look at the stack trace and error message. Is it still clear or has it been affected by the injection magic?

2024-05-31 16:24 UTC, aniketmaurya commented
@lantiga added a [test](https://github.com/Lightning-AI/LitServe/pull/118/files#diff-274978086d8b4f049cffd0a53c0a2b1634c323f7ae581e87427c3b0c9046716aR389) to make sure that correct error is shown to users in case of unhappy path - 

```
class SomeAPI(LitAPI):
    def predict(x, y):
        ...
```

2024-05-31 16:28 UTC, lantiga approved these changes
Looks good. We need to consider this an experimental feature, the UX may change in the future based on user feedback.

2024-05-31 16:28 UTC, lantiga commented on README.md
> +    <summary>✅ Track context throughout request lifecycle</summary>
```suggestion
    <summary>✅ Track context throughout the request lifecycle</summary>
```

2024-05-31 16:36 UTC, merged