[WIP] add auto accelerator
Lightning-AI/litserve pull request #44
Opened 2024-04-15 21:56 UTC by aniketmaurya

<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2024-04-16 00:46 UTC, williamFalcon commented on src/litserve/connector.py
> +import sys
when you write a new file please add the copyright notice @aniketmaurya

2024-04-17 20:17 UTC, aniketmaurya commented on src/litserve/connector.py
> +        if check_cuda_with_nvidia_smi():
`torch.cuda.is_available()` leads to multiprocessing error and recommends using `multiprocessing.set_start_method(‘spawn’)` which doesn't seem to work for Pipes on Linux.

2024-04-17 20:18 UTC, aniketmaurya commented on src/litserve/connector.py
> +        if "torch" in sys.modules:
@lantiga what do you think about having other frameworks here?

2024-04-19 13:15 UTC, lantiga requested changes
Looks good, a couple of points to address

2024-04-22 16:34 UTC, aniketmaurya commented on tests/test_lit_server.py
> +    assert server._connector.accelerator == expected_accelerator
added - https://github.com/Lightning-AI/litserve/pull/44/files#diff-274978086d8b4f049cffd0a53c0a2b1634c323f7ae581e87427c3b0c9046716aR260

2024-04-22 16:44 UTC, aniketmaurya commented on src/litserve/connector.py
> +                print("No GPU accelerator found, will default to cpu")
the exception was handled by defaulting to CPU when no GPU device were available. I have updated it to work without exception handling mechanism.

2024-04-22 18:01 UTC, lantiga approved these changes
Looks great!

We'll see if it's worth keeping the `Connector` abstraction in the future or if we can just flatten the logic down into the server. It may get more complicated in the future, in which case I'd keep it.

2024-04-22 18:01 UTC, merged