remove http timeout exception
Lightning-AI/litserve pull request #63
Opened 2024-04-24 20:24 UTC by aniketmaurya

<details>
  <summary><b>Before submitting</b></summa ry>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

This PR removes Timeout exception if server has accepted and started to process the request.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2024-04-29 14:29 UTC, lantiga requested changes
Looks to me like the middleware acts too early.

We need to timeout here:
https://github.com/Lightning-AI/litserve/pull/63/files#diff-9200e67a7e7d9ae3515b0d1ceb2cdc26e6575edf756f71287e9119a102515a50R395

if you’re hanging there waiting for too long AND your request hasn’t yet been popped from the queue, then we timeout

however if it has been popped from the queue, then we let it finish because it will compute anyway (we don’t cancel predictions that are being computed at this stage, we only remove the ones that are queued to prevent the queue to grow unbounded)

2024-04-29 14:29 UTC, lantiga commented on README.md
> +server = LitServer(SimpleLitAPI(), accelerator="cuda", devices=4, timeout=False)
Let's remove additional arguments and focus on the one we are introducing
```suggestion
server = LitServer(SimpleLitAPI(), timeout=False)
```

2024-04-30 05:04 UTC, aniketmaurya commented
@lantiga updated the PR as per feedback. now the requests will timeout only if it was waiting long in the queue.

2024-04-30 16:14 UTC, lantiga approved these changes

2024-04-30 16:14 UTC, lantiga commented on tests/test_simple.py
> +        assert response2.status_code == 504, "Server takes longer than specified timeout and request should timeout"
I'd also add an assert for response1.status_code

2024-04-30 16:15 UTC, lantiga commented
Nice async trick @aniketmaurya

2024-04-30 16:35 UTC, merged