document accelerator=auto
Lightning-AI/litserve pull request #64
Opened 2024-04-24 21:13 UTC by aniketmaurya

<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2024-04-25 14:45 UTC, lantiga requested changes
Added a request

2024-04-25 14:45 UTC, lantiga commented on README.md
> +The `accelerator` variable can be set to `"auto"`, and LitServe will select the appropriate GPU or CPU, whichever is available.
`auto` is already the default, we should not instruct users to add it explicitly

So, remove it from the code, and instead add a section (under and expanded advanced bullet) that says: `accelerator` is `auto` by default.

If you wish to perform explicit placement, then pass the device manually + example.

2024-04-27 17:40 UTC, williamFalcon commented on README.md
> +server = LitServer(SimpleLitAPI())
```suggestion
api = SimpleLitAPI()

# these two are equivalent
server = LitServer(api)
server = LitServer(api, accelerator='auto')
```

2024-04-27 17:41 UTC, williamFalcon commented on README.md
> +server = LitServer(api, accelerator='auto')
@lantiga @aniketmaurya 
this is how we should show things that happen automatically... an empty () doesn't show what this does correctly.

2024-04-29 11:59 UTC, lantiga approved these changes

2024-04-29 12:00 UTC, merged