[WIP] add readme improvements
Lightning-AI/litserve pull request #70
Opened 2024-04-30 17:21 UTC by aniketmaurya

<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2024-04-30 18:00 UTC, aniketmaurya commented on README.md
> +class SimpleBatchedAPI(ls.LitAPI):
sorry this was misnamed by me in #65

2024-04-30 19:01 UTC, lantiga requested changes
I would actually make the import explicit so the code remains cleaner

```
from litserve.examples import SimpleLitAPI
```

2024-04-30 19:01 UTC, lantiga commented on README.md
> +server = LitServer(ls.examples.SimplePyTorchAPI(), accelerator="cuda", devices=[0, 3])
```suggestion
server = LitServer(ls.examples.SimpleTorchAPI(), accelerator="cuda", devices=[0, 3])
```

2024-04-30 19:01 UTC, lantiga commented on README.md
> +server = LitServer(ls.examples.SimplePyTorchAPI(), accelerator="cuda", devices=4, workers_per_device=2)
```suggestion
server = LitServer(ls.examples.SimpleTorchAPI(), accelerator="cuda", devices=4, workers_per_device=2)
```

2024-04-30 23:33 UTC, aniketmaurya commented
CI should pass after #73

2024-05-02 15:31 UTC, aniketmaurya commented
@lantiga windows CI seems to hang for README code pytest.

2024-05-03 16:51 UTC, lantiga approved these changes

2024-05-03 16:51 UTC, merged